[workspace]

members = [
    "glasswing-core",
    "glasswing-tournament",
    "glasswing-perft",
    "glasswing-testing",
]

[profile.release]
overflow-checks = false
codegen-units = 1
opt-level = 3
lto = true